export const ERROR_CODES = [
  'VALIDATION_FAILED',
  'UNSUPPORTED_FORMAT',
  'CORRUPT_IMAGE',
  'ANIMATED_NOT_SUPPORTED',
  'IMAGE_TOO_LARGE_PIXELS',
  'FILE_TOO_LARGE',
  'TOO_MANY_FILES',
  'INVALID_CROP_RECT',
  'PHOTO_LARGER_THAN_PAPER',
  'LAYOUT_IMPOSSIBLE',
  'PROCESSING_TIMEOUT',
  'ENCODE_FAILED',
  'PDF_BUILD_FAILED',
  'RATE_LIMITED',
  'INTERNAL',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];

export const HTTP_STATUS_FOR: Readonly<Record<ErrorCode, number>> = Object.freeze({
  VALIDATION_FAILED: 400,
  UNSUPPORTED_FORMAT: 415,
  CORRUPT_IMAGE: 422,
  ANIMATED_NOT_SUPPORTED: 422,
  IMAGE_TOO_LARGE_PIXELS: 422,
  FILE_TOO_LARGE: 413,
  TOO_MANY_FILES: 413,
  INVALID_CROP_RECT: 400,
  PHOTO_LARGER_THAN_PAPER: 422,
  LAYOUT_IMPOSSIBLE: 422,
  PROCESSING_TIMEOUT: 504,
  ENCODE_FAILED: 500,
  PDF_BUILD_FAILED: 500,
  RATE_LIMITED: 429,
  INTERNAL: 500,
});

export const assertHttpStatus = (code: ErrorCode): number => {
  const status = HTTP_STATUS_FOR[code];
  return status;
};
